import os, re

base = os.path.join("D:", os.sep, "项目", "工作区", "工作5")
articles_dir = os.path.join(base, "articles")

with open(os.path.join(articles_dir, "ai-article-writer-2026.html"), "r", encoding="utf-8") as f:
    sample = f.read()

tb = sample[:sample.index('<article class="article-content">')]
ta = sample[sample.index("</article>") + 10:]

def create(file, title, desc, h1, body, keywords):
    url = "https://creatordir-tools.vercel.app/articles/" + file
    og_title = title + " - CreatorAI Tools"
    html = tb
    html = re.sub(r'<title>.*?</title>', f"<title>{og_title}</title>", html)
    html = re.sub(r'property="og:title" content="[^"]*"', f'property="og:title" content="{og_title}"', html)
    html = re.sub(r'property="og:description" content="[^"]*"', f'property="og:description" content="{desc}"', html)
    html = re.sub(r'property="og:url" content="[^"]*"', f'property="og:url" content="{url}"', html)
    html = re.sub(r'name="twitter:title" content="[^"]*"', f'name="twitter:title" content="{og_title}"', html)
    html = re.sub(r'name="twitter:description" content="[^"]*"', f'name="twitter:description" content="{desc}"', html)
    html = re.sub(r'name="description" content="[^"]*"', f'name="description" content="{desc}"', html)
    html = re.sub(r'name="keywords" content="[^"]*"', f'name="keywords" content="{keywords}"', html)
    html += '\n<article class="article-content">\n<h1>' + h1 + '</h1>\n<p class="article-meta">Published: 2026-06-22</p>\n' + body + '\n</article>\n' + ta
    with open(os.path.join(articles_dir, file), "w", encoding="utf-8") as f:
        f.write(html)
    print(f"Created: {file}")

articles = [
    ("chatgpt-vs-claude-vs-gemini-2026.html","ChatGPT vs Claude vs Gemini 2026 Best AI Assistant","Compare ChatGPT, Claude, and Gemini for content creation.","ChatGPT vs Claude vs Gemini 2026 Comparison","<p>Compare three leading AI assistants for content creation.</p><h2>ChatGPT</h2><p>Best versatility with GPT-4o. Free + $20/mo Plus.</p><h2>Claude</h2><p>Best for long-form writing with 200K context window.</p><h2>Gemini</h2><p>Best for Google Workspace integration. Free with Google.</p><p>Browse <a href=\"../tools/\">AI tools</a> for more.</p>","AI comparison, ChatGPT vs Claude, Gemini 2026"),
    ("jasper-vs-writesonic-vs-copyai-2026.html","Jasper vs Writesonic vs Copy.ai: Best AI Writing Tool","Compare Jasper, Writesonic, and Copy.ai for AI writing.","Jasper vs Writesonic vs Copy.ai: AI Writing Tools Compared","<p>Three leading AI writing tools compared.</p><h2>Jasper AI</h2><p>Best for long-form brand content. $49/mo.</p><h2>Writesonic</h2><p>Best value AI writing. GPT-4 powered. $19/mo.</p><h2>Copy.ai</h2><p>Best for workflow automation. $36/mo.</p><p>Browse <a href=\"../tools/\">AI writing tools</a>.</p>","Jasper vs Writesonic, Copy.ai, AI writing comparison"),
    ("best-free-ai-tools-2026.html","50 Best Free AI Tools for Creators 2026","The ultimate collection of free AI tools at zero cost.","50 Best Free AI Tools for Creators in 2026","<p>Hundreds of AI tools offer generous free tiers.</p><h2>Free Writing</h2><p>ChatGPT, Claude, Perplexity, Gemini</p><h2>Free Image</h2><p>Leonardo AI, Stable Diffusion, Canva</p><h2>Free Video</h2><p>CapCut, Runway, Pika Labs</p><h2>Free Audio</h2><p>ElevenLabs, MusicFX</p><p>Browse <a href=\"../tools/\">AI tools directory</a>.</p>","free AI tools, best free AI, no cost AI"),
    ("best-ai-tools-writers-2026.html","30 Best AI Tools for Writers 2026","Discover the best AI tools for writers.","30 Best AI Tools for Writers in 2026","<p>Writers leverage AI for every stage of content creation.</p><h2>Writing Assistants</h2><p>Jasper AI, Claude, ChatGPT, Grammarly</p><h2>Research Tools</h2><p>Perplexity, Scite, Elicit</p><h2>Publishing Tools</h2><p>Notion AI, Copy.ai, Writesonic</p><p>Browse <a href=\"../tools/\">AI writing tools</a>.</p>","AI tools for writers, writing AI, best writing tools"),
    ("best-ai-tools-marketers-2026.html","30 Best AI Tools for Marketers 2026","Boost marketing with AI: SEO, social media, email.","30 Best AI Tools for Marketers in 2026","<p>Marketers have more AI tools than ever.</p><h2>AI SEO Tools</h2><p>Semrush, Surfer SEO, Frase.io</p><h2>AI Social Media</h2><p>Hootsuite, Buffer, Later</p><h2>AI Email</h2><p>Mailchimp, ConvertKit, ActiveCampaign</p><p>Find all in <a href=\"../tools/\">AI tools directory</a>.</p>","AI tools for marketers, marketing AI, SEO AI"),
    ("best-ai-tools-students-2026.html","20 Best AI Tools for Students 2026","Ace your studies with AI: research, writing, notes.","20 Best AI Tools for Students in 2026","<p>Students can study smarter with AI tools.</p><h2>AI Writing</h2><p>ChatGPT, Claude, Grammarly</p><h2>AI Research</h2><p>Perplexity, Elicit, Scite</p><h2>AI Study</h2><p>Mem, Notion AI, Otter.ai</p><p>Browse <a href=\"../tools/\">AI tools directory</a>.</p>","AI tools students, study AI, academic AI"),
    ("best-ai-tools-developers-2026.html","25 Best AI Tools for Developers 2026","Supercharge development with AI coding tools.","25 Best AI Tools for Developers in 2026","<p>AI coding tools help developers write better code faster.</p><h2>AI Code</h2><p>GitHub Copilot, Cursor, Claude</p><h2>AI Development</h2><p>Bolt.new, Replit AI, Vercel</p><h2>AI Testing</h2><p>Testim, Mabl</p><p>Browse <a href=\"../tools/\">AI tools directory</a>.</p>","AI tools developers, coding AI, developer tools"),
    ("best-ai-tools-youtubers-2026.html","20 Best AI Tools for YouTubers 2026","Grow your YouTube channel with AI tools.","20 Best AI Tools for YouTubers in 2026","<p>YouTube creators use AI at every production stage.</p><h2>AI Scripting</h2><p>ChatGPT, Jasper</p><h2>AI Thumbnails</h2><p>Canva AI, Leonardo AI</p><h2>AI Editing</h2><p>Descript, CapCut, Runway</p><h2>AI SEO</h2><p>TubeBuddy, VidIQ</p><p>Find more in <a href=\"../tools/\">AI tools directory</a>.</p>","AI tools YouTubers, YouTube AI, video creation"),
    ("best-ai-tools-entrepreneurs-2026.html","25 Best AI Tools for Entrepreneurs 2026","Build and scale your business faster with AI.","25 Best AI Tools for Entrepreneurs in 2026","<p>Entrepreneurs use AI to move faster.</p><h2>AI Building</h2><p>GitHub Copilot, Bolt.new, Cursor</p><h2>AI Marketing</h2><p>Jasper, Semrush, Buffer</p><h2>AI Operations</h2><p>Notion AI, Motion, Zapier</p><p>Find in <a href=\"../tools/\">AI tools directory</a>.</p>","AI tools entrepreneurs, startup AI, business AI"),
    ("best-ai-tools-small-business-2026.html","30 Best AI Tools for Small Business 2026","Boost your small business with AI tools.","30 Best AI Tools for Small Business in 2026","<p>Small businesses compete with AI.</p><h2>AI Marketing</h2><p>Mailchimp, Canva, Hootsuite</p><h2>AI Operations</h2><p>Notion AI, Zapier, Motion</p><h2>AI Service</h2><p>Intercom, Zendesk AI</p><p>Find all in <a href=\"../tools/\">AI tools directory</a>.</p>","AI tools small business, SMB AI, business AI"),
    ("best-ai-tools-educators-2026.html","20 Best AI Tools for Educators 2026","Transform teaching with AI: planning, grading, content.","20 Best AI Tools for Educators in 2026","<p>AI helps educators save time.</p><h2>AI Planning</h2><p>ChatGPT, Khanmigo</p><h2>AI Grading</h2><p>Gradescope, Turnitin</p><h2>AI Content</h2><p>Canva AI, Synthesia, Descript</p><p>Find in <a href=\"../tools/\">AI tools directory</a>.</p>","AI tools educators, teaching AI, education AI"),
    ("best-ai-tools-photographers-2026.html","15 Best AI Tools for Photographers 2026","Enhance photography with AI editing tools.","15 Best AI Tools for Photographers in 2026","<p>AI revolutionizes photo post-processing.</p><h2>AI Editing</h2><p>Adobe Photoshop AI, Luminar Neo, Topaz Photo AI</p><h2>AI Organization</h2><p>Google Photos, Lightroom AI</p><h2>AI Generation</h2><p>Midjourney, DALL-E 3</p><p>Browse <a href=\"../tools/\">AI tools directory</a>.</p>","AI tools photographers, photo AI, photography AI"),
    ("ai-content-creation-workflow-2026.html","Complete AI Content Creation Workflow 2026","Step-by-step AI content workflow.","Complete AI Content Creation Workflow 2026","<p>Create content end-to-end with AI tools.</p><h2>1. Ideation</h2><p>ChatGPT for ideas. Claude for analysis.</p><h2>2. Writing</h2><p>Jasper for draft. Claude for editing.</p><h2>3. Visuals</h2><p>Canva AI for graphics. Midjourney for art.</p><h2>4. Distribution</h2><p>Buffer for scheduling. Surfer SEO for optimization.</p><p>Browse <a href=\"../tools/\">AI tools directory</a>.</p>","AI workflow, content creation, content automation"),
    ("how-to-make-money-with-ai-2026.html","How to Make Money with AI Tools in 2026","Proven strategies to monetize AI tools.","How to Make Money with AI Tools in 2026","<p>AI tools create new income opportunities.</p><h2>1. AI Freelancing</h2><p>Offer AI-enhanced services. Charge premium rates.</p><h2>2. AI Content Business</h2><p>Build directories. Use affiliate marketing.</p><h2>3. AI Consulting</h2><p>Help businesses implement AI tools.</p><h2>4. Digital Products</h2><p>Sell AI-generated templates and art.</p><p>Browse <a href=\"../tools/\">AI tools</a> to start.</p>","make money AI, AI freelancing, monetize AI"),
    ("ai-for-seo-guide-2026.html","AI for SEO: Complete Guide 2026","Master SEO with AI tools and strategies.","AI for SEO: Complete Guide 2026","<p>AI tools make SEO more effective.</p><h2>Keyword Research</h2><p>Semrush and Ahrefs identify high-value keywords.</p><h2>Content Optimization</h2><p>Surfer SEO provides data-driven recommendations.</p><h2>Content Writing</h2><p>Jasper generates SEO-optimized content.</p><p>Find <a href=\"../tools/\">AI SEO tools</a>.</p>","AI SEO guide, SEO content, content optimization"),
    ("ai-for-video-production-guide-2026.html","AI for Video Production: Complete Guide 2026","Create professional videos with AI.","AI for Video Production: Complete Guide 2026","<p>AI makes professional video production accessible.</p><h2>Script to Video</h2><p>Invideo AI converts scripts into complete videos.</p><h2>AI Editing</h2><p>Descript and Runway automate editing and effects.</p><h2>AI Voiceovers</h2><p>ElevenLabs generates realistic voiceovers.</p><p>Browse <a href=\"../tools/\">AI video tools</a>.</p>","AI video production, video creation, AI editing"),
    ("ai-for-social-media-guide-2026.html","AI for Social Media: Complete Guide 2026","Automate social media with AI tools.","AI for Social Media: Complete Guide 2026","<p>AI tools automate your social media presence.</p><h2>Scheduling</h2><p>Hootsuite and Buffer for optimal timing.</p><h2>Content</h2><p>Generate captions with ChatGPT and Canva AI.</p><h2>Analytics</h2><p>Track performance with AI insights.</p><p>Browse <a href=\"../tools/\">AI social tools</a>.</p>","AI social media, social automation, content AI"),
    ("ai-for-podcasting-guide-2026.html","AI for Podcasting: Complete Guide 2026","Start a podcast with AI tools.","AI for Podcasting: Complete Guide 2026","<p>AI streamlines podcast production.</p><h2>Recording</h2><p>Riverside.fm records high-quality audio.</p><h2>Editing</h2><p>Descript edits audio by editing text.</p><h2>Distribution</h2><p>Buzzsprout generates show notes automatically.</p><p>Browse <a href=\"../tools/\">AI audio tools</a>.</p>","AI podcast, podcast AI, audio production"),
    ("ai-for-email-marketing-guide-2026.html","AI for Email Marketing: Complete Guide 2026","Optimize email marketing with AI.","AI for Email Marketing: Complete Guide 2026","<p>AI makes email marketing more effective.</p><h2>Subject Lines</h2><p>Generate compelling subject lines that increase opens.</p><h2>Content</h2><p>Personalize email content with AI.</p><h2>Analytics</h2><p>Track and optimize campaigns.</p><p>Find <a href=\"../tools/\">AI email tools</a>.</p>","AI email marketing, email AI, marketing automation"),
    ("ai-for-ecommerce-guide-2026.html","AI for E-commerce: Complete Guide 2026","Boost your online store with AI.","AI for E-commerce: Complete Guide 2026","<p>E-commerce businesses leverage AI across the customer journey.</p><h2>Product Content</h2><p>Generate descriptions with AI writing tools.</p><h2>Recommendations</h2><p>AI recommendations increase order value.</p><h2>Service</h2><p>AI chatbots provide 24/7 support.</p><p>Browse <a href=\"../tools/\">AI tools</a>.</p>","AI e-commerce, online store AI, ecommerce AI"),
    ("ai-for-freelancers-guide-2026.html","AI for Freelancers: Complete Guide 2026","Grow your freelance business with AI.","AI for Freelancers: Complete Guide 2026","<p>Freelancers leverage AI to win more clients.</p><h2>Proposals</h2><p>Generate winning proposals with ChatGPT.</p><h2>Delivery</h2><p>Use AI tools for higher quality work faster.</p><h2>Management</h2><p>Notion AI and Motion for project management.</p><p>Browse <a href=\"../tools/\">AI tools</a>.</p>","AI freelancers, freelance AI, freelancer tools"),
    ("ai-writing-tools-complete-guide-2026.html","AI Writing Tools: Complete Guide 2026","Everything about AI writing tools.","AI Writing Tools: Complete Guide 2026","<p>AI writing tools are essential for content creators.</p><h2>Types</h2><p>Long-form: Jasper, Claude. Short-form: Copy.ai. Editing: Grammarly.</p><h2>How to Choose</h2><p>Consider content type, budget, and team size.</p><h2>Best Practices</h2><p>Use AI for first drafts. Edit for quality. Add personal voice.</p><p>Browse <a href=\"../tools/\">AI writing tools</a>.</p>","AI writing guide, writing AI, content AI"),
    ("ai-image-tools-complete-guide-2026.html","AI Image Tools: Complete Guide 2026","Everything about AI image generation.","AI Image Tools: Complete Guide 2026","<p>AI image generation transforms visual content creation.</p><h2>Top Tools</h2><p>Midjourney for art. DALL-E for commercial. Stable Diffusion for control.</p><h2>Prompt Writing</h2><p>Be specific. Include style and composition. Iterate for results.</p><h2>Commercial Use</h2><p>Check each tool's commercial terms before using.</p><p>Browse <a href=\"../tools/\">AI image tools</a>.</p>","AI image guide, image generation, AI art"),
    ("ai-video-tools-complete-guide-2026.html","AI Video Tools: Complete Guide 2026","Everything about AI video creation.","AI Video Tools: Complete Guide 2026","<p>AI video tools revolutionize content production.</p><h2>Generation</h2><p>Runway and Pika create video from text.</p><h2>Editing</h2><p>Descript edits by text. CapCut offers auto-captions.</p><h2>Avatars</h2><p>Synthesia and HeyGen create presenter videos.</p><p>Browse <a href=\"../tools/\">AI video tools</a>.</p>","AI video guide, video AI, video creation"),
    ("ai-marketing-tools-complete-guide-2026.html","AI Marketing Tools: Complete Guide 2026","Everything about AI marketing tools.","AI Marketing Tools: Complete Guide 2026","<p>AI transforms every aspect of marketing.</p><h2>SEO</h2><p>Semrush for research. Surfer SEO for optimization.</p><h2>Social Media</h2><p>Hootsuite and Buffer for scheduling.</p><h2>Email</h2><p>Mailchimp for campaigns. ConvertKit for creators.</p><p>Browse <a href=\"../tools/\">AI marketing tools</a>.</p>","AI marketing guide, marketing AI, digital marketing"),
    ("ai-tools-content-marketing-2026.html","Best AI Tools for Content Marketing 2026","Complete guide to AI content marketing.","Best AI Tools for Content Marketing 2026","<p>Content marketing is effective. AI makes it easier.</p><h2>Strategy</h2><p>Semrush for research. Frase for topic clusters.</p><h2>Creation</h2><p>Jasper for blogs. Canva for visuals. Descript for video.</p><h2>Distribution</h2><p>Buffer for scheduling. Surfer SEO for optimization.</p><p>Browse <a href=\"../tools/\">AI tools</a>.</p>","content marketing AI, AI marketing tools, content strategy"),
]

for article in articles:
    create(*article)

print(f"\nTotal: {len(articles)} new articles created")

# Count
existing = os.listdir(articles_dir)
html_count = len([f for f in existing if f.endswith(".html")])
print(f"Total HTML articles: {html_count}")
